# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo.xci
# IP: The module: 'system_big_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo/system_big_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_big_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo/system_big_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_big_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_big_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo.xci
# IP: The module: 'system_big_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo/system_big_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_big_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo/system_big_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_big_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.srcs/sources_1/ip/fifo_generator_v9_3_0/system_big_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_big_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
