# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo.xci
# IP: The module: 'ch_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo/ch_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ch_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo/ch_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ch_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ch_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo.xci
# IP: The module: 'ch_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo/ch_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ch_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo/ch_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ch_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/share/V7_bufh_place_v2_0/V7_bufh_place_v2_0.srcs/sources_1/ip/ch_fifo/ch_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ch_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
