# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2
set_property target_language Verilog [current_project]
set_property board xilinx.com:virtex7:vc707:1.1 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
set_property use_blackbox_stub false [get_files D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]

read_ip D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/sources_1/ip/ila_0_0/ila_0.xci
set_property used_in_implementation false [get_files -all d:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/sources_1/ip/ila_0_0/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/sources_1/ip/ila_0_0/ila_0_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/sources_1/ip/ila_0_0/ila_0.xci]

read_verilog {
  D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/sources_1/imports/tdc_front_top.v
  d:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_stub.v
}
read_xdc D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/constrs_1/tdc_front_top.xdc
set_property used_in_implementation false [get_files D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.srcs/constrs_1/tdc_front_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc/multiple_channel_wOnboardOsc.data/wt [current_project]
set_property parent.project_dir D:/RHEL_work/MyGit/tp_gen/multi_ch_wOnBDOsc [current_project]
synth_design -top tdc_front_top -part xc7vx485tffg1761-2
write_checkpoint tdc_front_top.dcp
report_utilization -file tdc_front_top_utilization_synth.rpt -pb tdc_front_top_utilization_synth.pb
