# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: tdc_front_top.xdc

# Block Designs: bd/axi_system/axi_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system || ORIG_REF_NAME==axi_system}]

# IP: bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_chip2chip_0_0 || ORIG_REF_NAME==axi_system_axi_chip2chip_0_0}]

# IP: bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_proc_sys_reset_0_0 || ORIG_REF_NAME==axi_system_proc_sys_reset_0_0}]

# IP: bd/axi_system/ip/axi_system_axi4lite_gp_0_0/axi_system_axi4lite_gp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi4lite_gp_0_0 || ORIG_REF_NAME==axi_system_axi4lite_gp_0_0}]

# IP: bd/axi_system/ip/axi_system_axi_interconnect_0_0/axi_system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_interconnect_0_0 || ORIG_REF_NAME==axi_system_axi_interconnect_0_0}]

# IP: bd/axi_system/ip/axi_system_axi_protocol_converter_1_0/axi_system_axi_protocol_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_protocol_converter_1_0 || ORIG_REF_NAME==axi_system_axi_protocol_converter_1_0}]

# IP: bd/axi_system/ip/axi_system_mig_7series_0_0/axi_system_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_mig_7series_0_0 || ORIG_REF_NAME==axi_system_mig_7series_0_0}]

# IP: bd/axi_system/ip/axi_system_gen_test_pulse_lite_0_0/axi_system_gen_test_pulse_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_gen_test_pulse_lite_0_0 || ORIG_REF_NAME==axi_system_gen_test_pulse_lite_0_0}]

# IP: bd/axi_system/ip/axi_system_axi_protocol_converter_2_0/axi_system_axi_protocol_converter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_protocol_converter_2_0 || ORIG_REF_NAME==axi_system_axi_protocol_converter_2_0}]

# IP: bd/axi_system/ip/axi_system_regfiles_lite_0_0/axi_system_regfiles_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_regfiles_lite_0_0 || ORIG_REF_NAME==axi_system_regfiles_lite_0_0}]

# IP: bd/axi_system/ip/axi_system_axi_protocol_converter_3_0/axi_system_axi_protocol_converter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_protocol_converter_3_0 || ORIG_REF_NAME==axi_system_axi_protocol_converter_3_0}]

# IP: bd/axi_system/ip/axi_system_tdc_calib_capture_lite_0_0/axi_system_tdc_calib_capture_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_tdc_calib_capture_lite_0_0 || ORIG_REF_NAME==axi_system_tdc_calib_capture_lite_0_0}]

# IP: bd/axi_system/ip/axi_system_axi_protocol_converter_4_0/axi_system_axi_protocol_converter_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_protocol_converter_4_0 || ORIG_REF_NAME==axi_system_axi_protocol_converter_4_0}]

# IP: bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_dma_0_0 || ORIG_REF_NAME==axi_system_axi_dma_0_0}]

# IP: bd/axi_system/ip/axi_system_fifo2ddr_0_0/axi_system_fifo2ddr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_fifo2ddr_0_0 || ORIG_REF_NAME==axi_system_fifo2ddr_0_0}]

# IP: bd/axi_system/ip/axi_system_axi_protocol_converter_5_0/axi_system_axi_protocol_converter_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_axi_protocol_converter_5_0 || ORIG_REF_NAME==axi_system_axi_protocol_converter_5_0}]

# IP: bd/axi_system/ip/axi_system_xbar_0/axi_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_xbar_0 || ORIG_REF_NAME==axi_system_xbar_0}]

# IP: bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_proc_sys_reset_1_0 || ORIG_REF_NAME==axi_system_proc_sys_reset_1_0}]

# IP: bd/axi_system/ip/axi_system_s00_data_fifo_0/axi_system_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_s00_data_fifo_0 || ORIG_REF_NAME==axi_system_s00_data_fifo_0}]

# IP: bd/axi_system/ip/axi_system_s01_data_fifo_0/axi_system_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_s01_data_fifo_0 || ORIG_REF_NAME==axi_system_s01_data_fifo_0}]

# IP: bd/axi_system/ip/axi_system_m01_data_fifo_0/axi_system_m01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_m01_data_fifo_0 || ORIG_REF_NAME==axi_system_m01_data_fifo_0}]

# IP: bd/axi_system/ip/axi_system_auto_cc_0/axi_system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_auto_cc_0 || ORIG_REF_NAME==axi_system_auto_cc_0}]

# XDC: bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_axi_chip2chip_0_0 || ORIG_REF_NAME==axi_system_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_axi_chip2chip_0_0 || ORIG_REF_NAME==axi_system_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_proc_sys_reset_0_0 || ORIG_REF_NAME==axi_system_proc_sys_reset_0_0}]

# XDC: bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_proc_sys_reset_0_0 || ORIG_REF_NAME==axi_system_proc_sys_reset_0_0}]

# XDC: bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_axi_protocol_converter_1_0/axi_system_axi_protocol_converter_1_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_mig_7series_0_0/axi_system_mig_7series_0_0/user_design/constraints/axi_system_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_mig_7series_0_0 || ORIG_REF_NAME==axi_system_mig_7series_0_0}]

# XDC: bd/axi_system/ip/axi_system_mig_7series_0_0/axi_system_mig_7series_0_0/user_design/constraints/axi_system_mig_7series_0_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_axi_protocol_converter_2_0/axi_system_axi_protocol_converter_2_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_axi_protocol_converter_3_0/axi_system_axi_protocol_converter_3_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_axi_protocol_converter_4_0/axi_system_axi_protocol_converter_4_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_axi_dma_0_0 || ORIG_REF_NAME==axi_system_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_axi_dma_0_0 || ORIG_REF_NAME==axi_system_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/axi_system/ip/axi_system_axi_protocol_converter_5_0/axi_system_axi_protocol_converter_5_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_xbar_0/axi_system_xbar_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_proc_sys_reset_1_0 || ORIG_REF_NAME==axi_system_proc_sys_reset_1_0}]

# XDC: bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_system_proc_sys_reset_1_0 || ORIG_REF_NAME==axi_system_proc_sys_reset_1_0}]

# XDC: bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_s00_data_fifo_0/axi_system_s00_data_fifo_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_s01_data_fifo_0/axi_system_s01_data_fifo_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_m01_data_fifo_0/axi_system_m01_data_fifo_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_auto_cc_0/axi_system_auto_cc_0_ooc.xdc

# XDC: bd/axi_system/ip/axi_system_auto_cc_0/axi_system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_auto_cc_0 || ORIG_REF_NAME==axi_system_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/axi_system/axi_system_ooc.xdc
