# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/share/tmp/V7_bufh_place/V7_bufh_place.cache/wt [current_project]
set_property parent.project_path /mnt/share/tmp/V7_bufh_place/V7_bufh_place.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/axi4lite_gp_1.0_0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/gen_test_pulse_lite_1.0_0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/regfiles_lite_1.0_0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/tdc_calib_capture_lite_1.0_0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/fifo2ddr_v1_0_project_0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/axi4lite_gp_1.0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/gen_test_pulse_lite_1.0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/regfiles_lite_1.0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/tdc_calib_capture_lite_1.0
  /home/skim/tdc_64ch_v2/V7_v2/V7_20151114_hixfer_3/V7_20151114_hixfer_3.ipdefs/fifo2ddr_v1_0_project
} [current_project]
add_files -quiet /mnt/share/tmp/V7_bufh_place/V7_bufh_place.runs/ch_fifo_synth_1/ch_fifo.dcp
set_property used_in_implementation false [get_files /mnt/share/tmp/V7_bufh_place/V7_bufh_place.runs/ch_fifo_synth_1/ch_fifo.dcp]
add_files -quiet /mnt/share/tmp/V7_bufh_place/V7_bufh_place.runs/system_big_fifo_synth_1/system_big_fifo.dcp
set_property used_in_implementation false [get_files /mnt/share/tmp/V7_bufh_place/V7_bufh_place.runs/system_big_fifo_synth_1/system_big_fifo.dcp]
add_files /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/axi_system.bd
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_chip2chip_0_0/axi_system_axi_chip2chip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_proc_sys_reset_0_0/axi_system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_protocol_converter_1_0/axi_system_axi_protocol_converter_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_mig_7series_0_0/axi_system_mig_7series_0_0/user_design/constraints/axi_system_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_mig_7series_0_0/axi_system_mig_7series_0_0/user_design/constraints/axi_system_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_protocol_converter_2_0/axi_system_axi_protocol_converter_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_protocol_converter_3_0/axi_system_axi_protocol_converter_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_protocol_converter_4_0/axi_system_axi_protocol_converter_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_dma_0_0/axi_system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_axi_protocol_converter_5_0/axi_system_axi_protocol_converter_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_xbar_0/axi_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_proc_sys_reset_1_0/axi_system_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_s00_data_fifo_0/axi_system_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_s01_data_fifo_0/axi_system_s01_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_m01_data_fifo_0/axi_system_m01_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_auto_cc_0/axi_system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/ip/axi_system_auto_cc_0/axi_system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/axi_system_ooc.xdc]
set_property is_locked true [get_files /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/axi_system.bd]

read_verilog -library xil_defaultlib {
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/tp_gen.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/rle_enc_tdc_en.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/front_dFFs_v4.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/front_dFFs_v3.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/rle_enc_v2.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/tdc_en.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/range_gate_con.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/ps_con.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/high_speed_trans.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/front_TDC_1ch_cs.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/DSI.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/clk_mmcme_main.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/bd/axi_system/hdl/axi_system_wrapper.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/front_TDC_1ch.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/SPI_CLK.v
  /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/sources_1/imports/tdc_front_top.v
}
read_xdc /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/constrs_1/tdc_front_top.xdc
set_property used_in_implementation false [get_files /mnt/share/tmp/V7_bufh_place/V7_bufh_place.srcs/constrs_1/tdc_front_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top tdc_front_top -part xc7vx485tffg1761-2 -fanout_limit 50 -keep_equivalent_registers
write_checkpoint -noxdef tdc_front_top.dcp
catch { report_utilization -file tdc_front_top_utilization_synth.rpt -pb tdc_front_top_utilization_synth.pb }
